Create Table FunctionalArea(Id int PRIMARY KEY NOT NULL,
							FunctionalAreaName varchar(50),
							CreatedOn datetime,
							CreatedBy varchar(50),
							LastModifiedBy varchar(50),
							LastModifiedOn datetime)
Create Table Industry(Id int PRIMARY KEY NOT NULL, IndustryName varchar(50))
Create Table UserProjects(Id varchar(50) PRIMARY KEY NOT NULL,
						  ProjectName varchar(20),
						  UserId varchar(50),
						  CreatedOn datetime,
						  CreatedBy varchar(50),
						  LastModifiedOn datetime,
						  LastModifiedBy varchar(50),
						  ProjectId int)
Create Table Project(Id int PRIMARY KEY NOT NULL,
					ProjectName varchar(50),
					CreatedOn datetime,
					CreatedBy varchar(50),
					LastModifiedBy varchar(50),
					LastModifiedOn datetime)
Create Table Questionnaire(QuestionnaireId varchar(50)  PRIMARY KEY NOT NULL,
							ProjectId varchar(50),
							QuestionId int,
							InScope bit,
							Criticality int,
							CreatedOn datetime,
							CreatedBy varchar(50),
							LastModifiedOn datetime,
							LastModifiedBy varchar(50))
Create Table QuestionResponse(ResponseId varchar(50) PRIMARY KEY NOT NULL,
								QuestionnaireId varchar(50),
								ProjectId varchar(50),
								Response varchar(10),
								Impact varchar(10),
								Effort varchar(10),
								Timing varchar(10),
								Observation varchar(1000),
								Recommendations varchar(1000),
								CreatedOn datetime,
								CreatedBy varchar(50),
								LastModifiedOn datetime,
								LastModifiedBy varchar(50))
Create Table Questions(QuestionId int PRIMARY KEY NOT NULL,
						FunctionAreaId int,
						QuestionName varchar(1000),
						Description varchar(1000),
						CreatedOn datetime,
						CreatedBy varchar(50),
						LastModifiedOn datetime,
						LastModifiedBy varchar(50),
						IndustryId int)
Create Table Register(Id varchar(50) PRIMARY KEY NOT NULL,
						FirstName varchar(100),
						LastName varchar(100),
						Email varchar(100))
Create Table Role(Id varchar(50) PRIMARY KEY NOT NULL,
					RoleName  varchar(20))
Create Table Score(ScoreId int PRIMARY KEY NOT NULL,
					ProjectId varchar(50),
					FunctionalAreaId int,
					ScoreValue int)
Create Table UserRole(UserRoleId varchar(50) PRIMARY KEY NOT NULL,
						RoleId varchar(50),
						Firstname varchar(50),
						Lastname varchar(50),
						Email varchar(50),
						CreatedOn datetime,
						CreatedBy varchar(50),
						LastModifiedOn datetime,
						LastModifiedBy varchar(50),
						UserId varchar(50),
						UserStatus int,
						UserName varchar(50))
Create Table Users(Id varchar(50)  PRIMARY KEY NOT NULL,
					Firstname varchar(50),
					Lastname varchar(50),
					Email varchar(50))